### ISSUE TITLE
Do we really need the examples?

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/rendezvous-server#9]
I am not sure how much value they are adding over the examples that already exist in the rust-libp2p repository. I'd rather keep this repository simple.

**Comment by rishflab** [comment]
In rust-libp2p the examples use identify which makes them incompatible with our rendezvous-server implementation. I made these examples so we have something we can use to test the rendezvous-server. I am not sure what @da-kami is using to test the rendezvous server atm. If they are not being used for that purpose and we do not intend to use them for e2e tests then we can remove them.

**Comment by thomaseizinger** [comment]
> In rust-libp2p the examples use identify which makes them incompatible with our rendezvous-server implementation.

Fair. Why don't we add an example that doesn't use identify then? Seems that would be more useful directly next to the implementation rather than here!

**Comment by rishflab** [comment]
> > In rust-libp2p the examples use identify which makes them incompatible with our rendezvous-server implementation.
> 
> Fair. Why don't we add an example that doesn't use identify then? Seems that would be more useful directly next to the implementation rather than here!

yep that's probably the way to go
